### ISSUE TITLE
[bug] missing field `version` - should not report

### ISSUE THREAD

**Issue by 1oglop1** [bnjbvr/cargo-machete#101]
Hi I have a `Cargo.toml` file without version and machete is failing 
with
```
  |
1 | [package]
  | ^^^^^^^^^
missing field `version`
```
However, the `version` field is optional and has been for some time already.
https://doc.rust-lang.org/cargo/reference/manifest.html#the-version-field

**Comment by bnjbvr** [comment]
Thanks for opening an issue, it might be one of the dependencies used for parsing that's responsible of that. Would you be interested in solving this with a pull request?

**Comment by 1oglop1** [comment]
I am not really a Rust magician, but it looks like you have pointed in the right direction: 

https://gitlab.com/lib.rs/cargo_toml/-/blob/main/src/cargo_toml.rs?ref_type=heads#L1540-1545

I will try to open an issue there and see if anything comes out of it.

**Comment by kornelski** [comment]
`cargo_toml` supports optional `version`, but you're using outdated `cargo_toml`.

**Comment by dspicher** [comment]
@bnjbvr would you consider making a release to give access this fix? Would be great!

**Comment by bnjbvr** [comment]
@dspicher yes, doing this now in #108

**Comment by dspicher** [comment]
Thanks!
