### ISSUE TITLE
No logo / mascot

### ISSUE THREAD

**Issue by feiss** [bnjbvr/cargo-machete#102]
Bonne soirée! 

I have a little present for you :)

Please please don't feel forced to use it. Do whatever you want, it's yours now ❤️ 

[cargo-machete-logo.zip](https://github.com/bnjbvr/cargo-machete/files/14230055/cargo-machete-logo.zip)

![cargo-machete-logo](https://github.com/bnjbvr/cargo-machete/assets/359872/0b88cdc3-b860-4100-b44c-b66a72a443ae)

**Comment by bnjbvr** [comment]
<3 Thanks again for drawing this logo Diego, it's just pure awesomeness!
