### ISSUE TITLE
Github Action fails in CI on windows-latest

### ISSUE THREAD

**Issue by Roms1383** [bnjbvr/cargo-machete#110]
Hi I've just discovered, tried and adopted right away `cargo-machete` ❤️  Great crate !

When [setting it up](https://github.com/cyb3rpsych0s1s/audioware/commit/58ccaef382fa83316eb6c27b1dd344cbef26c4a5) in Github workflow, I ran into some error on `windows-latest`:
```sh
error: could not compile `cargo-machete` (bin "cargo-machete") due to 1 previous error
error: failed to compile `cargo-machete v0.6.1`, intermediate artifacts can be found at `C:\Users\RUNNER~1\AppData\Local\Temp\cargo-install5qeHSQ`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
Error: The process 'C:\Users\runneradmin\.cargo\bin\cargo.exe' failed with exit code 101
```
➡️ [full details available in Action](https://github.com/cyb3rpsych0s1s/audioware/actions/runs/8006357482/job/21867901443).

💡 A simple alternative is to install it with `taiki-e/install-action`, [as in following commit](https://github.com/cyb3rpsych0s1s/audioware/commit/48504c8f5c15b6bf60fba39cc646466761c5a867).
> note that here the workflow failed for **another reason**: that I had unused dependencies indeed 😄

Hope this helps !

**Comment by bnjbvr** [comment]
Thanks for opening an issue. Not sure what's going on, as the error seems to be a link error, and I haven't seen it when compiling cargo-machete for the release builds, e.g. https://github.com/bnjbvr/cargo-machete/actions/runs/7991084257/job/21821428552

**Comment by Roms1383** [comment]
That could utterly be a false-positive, especially since I have a slightly exotic setup.
What about closing it for now? If ever somebody else run into it, they can just re-open it later on.
