### ISSUE TITLE
[Rust 1.77.0] cargo machete --with-metadata panicking

### ISSUE THREAD

**Issue by utkarshgupta137** [bnjbvr/cargo-machete#114]
The new stable version was just released & the crate is panicking when run with `--with-metadata`.
```
Analyzing dependencies of crates in this directory...
thread '<unnamed>' panicked at src/search_unused.rs:362:14:
the current package must be in the dependency graph
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at src/search_unused.rs:362:14:
the current package must be in the dependency graph
thread '<unnamed>' panicked at src/search_unused.rs:362:14:
the current package must be in the dependency graph
thread '<unnamed>' panicked at src/search_unused.rs:362:14:
the current package must be in the dependency graph
```
This happens about 19 times in the polars workspace: https://github.com/pola-rs/polars

**Comment by bnjbvr** [comment]
Thanks for opening an issue; could you try out https://github.com/bnjbvr/cargo-machete/pull/106 and let me know if it works on Windows, please?

**Comment by utkarshgupta137** [comment]
Oh I missed it. I'm on macOS (Apple Silicon), but this is working. I don't have access to a Windows setup at the moment.
