### ISSUE TITLE
Related dependencies are signed as unused but they are not

### ISSUE THREAD

**Issue by neutrinoks** [bnjbvr/cargo-machete#128]
Hello guys,

I faced an issue when using the `cargo machete` and the `proptest` and `proptest-derive` crates. In my current project, they are marked as optional (not sure if this is relevant). Machete suggests removing `protest` because it is not used obviously in the code, but I will get compilation errors when I remove it. It is needed when using the derive macro `Arbitrary` of `protest-derive`. Unfortunately it is a private repository and I cannot share it.

Regards, Michael

**Comment by bnjbvr** [comment]
Hi! Can you make another public example repository which reproduces the issue, please?

**Comment by neutrinoks** [comment]
Unfortunately, I am too busy currently, and because the effects I had were in a huge private repo, it is hard to reproduce that in a mockup project. I will observe it and come back to this issue later again.
