### ISSUE TITLE
Allow specifying known false positives in Cargo.toml

### ISSUE THREAD

**Issue by bnjbvr** [bnjbvr/cargo-machete#2]
This would allow running `cargo-machete` in CI, if one can enter a set of known false positives. It would be nice to reuse the same format as `cargo-udeps` for that: https://github.com/est31/cargo-udeps#ignoring-some-of-the-dependencies

**Comment by daniel5151** [comment]
Heyo - just chiming in to say that this'd be super useful! I've been looking for a good way to avoid introducing unused deps in some larger projects I've worked on, and cargo-machete seems to hit the best balance of all the existing tools wrt. performance, simplicity, and accuracy.

Given that you're already parsing the Cargo.toml files, it shouldn't be too difficult to introduce a `[package.metadata.cargo-machete]` section to specify false-positive deps

**Comment by daniel5151** [comment]
Nice, looks like `cargo_toml::Manifest` even includes a way to specify a metadata format to automatically look for!

e.g:

```rust
#[derive(serde::Serialize, serde::Deserialize)]
pub struct Metadata {
    #[serde(rename = "cargo-machete")]
    pub cargo_machete: Option<Ignored>,
}

#[derive(serde::Serialize, serde::Deserialize)]
pub struct Ignored {
    pub ignored: Vec<String>,
}

pub(crate) struct PackageAnalysis {
    pub manifest: cargo_toml::Manifest<Metadata>,
    ...
}
```

Which can then be used as:

```toml
# in Cargo.toml

[package.metadata.cargo-machete]
ignored = ["foo", "bar"]
```

I don't mind pushing up a PR sometime this weekend that implements this, though it's simple enough that either of us could hack something together pretty quickly. The only remaining question is bikeshedding on what particular schema to use for the metadata :)

**Comment by bnjbvr** [comment]
Sweet, thanks for the kind words too! Would be happy to take such a PR ☺️ We could take some inspiration from udeps, probably (even if the simplest thing, i.e. an array of dependency names, could be just fine)
