### ISSUE TITLE
cargo-machette is both a cargo subcommand a direct command except when it isn't

### ISSUE THREAD

**Issue by epage** [bnjbvr/cargo-machete#22]
// ...and the "machete" command if ran as cargo subcommand.
        if i == 1 && arg == "machete" {
            continue;
        }

Since your command accepts positional arguments, this will not allow me to run `cargo-machette machette` where `machette` is a directory but I'd have to know to run `cargo-machette machette machette`.   Personally, I find it dubious to have a command be dual natured (run in either cargo or out) especially when accepting positional arguments.

**Comment by bnjbvr** [comment]
You're very right. I didn't quite know how other tools handle this in particular, so I'm happy taking whichever approach is the most appropriate here!
