### ISSUE TITLE
Provide pre-compiled binaries

### ISSUE THREAD

**Issue by Veetaha** [bnjbvr/cargo-machete#30]
It would be awesome if `cargo-machete` could provide pre-compiled binaries making it much faster to download from CI.
See [`typos` CLI](https://github.com/crate-ci/typos/releases) that uses github Release to upload pre-compiled binaries of their `typos` CLI.

**Comment by bnjbvr** [comment]
Surely would be nice to do! It seems all of it can be done in Github via workflows, after a quick skim of what `typos` does, so anybody can feel free to start working on this and I'll provide help with repo admin (setting up secrets, running workflows, etc.).

**Comment by bnjbvr** [comment]
Forgot to close this one: this is now done via a github action, see https://github.com/bnjbvr/cargo-machete/releases. Thanks for opening that issue!
