### ISSUE TITLE
False positive with humantime_serde

### ISSUE THREAD

**Issue by oriontvv** [bnjbvr/cargo-machete#37]
Hi, folk. Thanks for this crate!
I got false positive error while using [humantime_serde](https://crates.io/crates/humantime-serde) crate

```rust
pub struct Settings {
    #[serde(with = "humantime_serde")]
    some_duration: Duration,
}
```
output:
```
my_crate -- /builds/..my_crate/Cargo.toml:
	humantime-serde
```

Is it possible to fix that?

**Comment by bnjbvr** [comment]
Hey, thanks for opening an issue. At first glance this is one of these cases that hides generated code behind a proc-macro, so grepping the code as text like cargo-machete does won't find it. [Proc-macros generate false positives and it's unfortunatly a well-known limitation of this tool](https://blog.benj.me/2022/04/27/cargo-machete/#a-tedious-process-calls-for-automation-so-i-made-a-tool). You can add an exception in your Cargo.toml though; see readme.
