### ISSUE TITLE
support new cargo package table workspaces

### ISSUE THREAD

**Issue by msalib** [bnjbvr/cargo-machete#41]
Newer versions of cargo let you specify crate metadata in the workspace and then inherit in each crate, but `cargo-machete` fails with this error when we do that:

```
error when handling /XXXX/Cargo.toml: invalid type: map, expected a string for key `package.version` at line 3 column 21
```

See [here](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table) for more details.

And thanks for a wonderful tool that's been super helpful!

**Comment by bnjbvr** [comment]
Thanks for the kind words. And yes, definitely something I'd like to support! I wonder if it's a matter of updating cargo-machete's dependencies that parse the Cargo.toml files, or if there'd be more we'd have to do.

**Comment by bnjbvr** [comment]
[This is planned](https://gitlab.com/crates.rs/cargo_toml/-/issues/19) in the crate parsing the TOML files, but not implemented yet. I'll keep this issue as a reminder to update in cargo-machete once that's ready.
