### ISSUE TITLE
Introduce clap for command line argument parsing

### ISSUE THREAD

**Issue by mickvangelderen** [bnjbvr/cargo-machete#50]
`clap` with it's derive feature is very easy to use and yields a great command line application, I would consider using this as more arguments and flags are getting added.

**Comment by bnjbvr** [comment]
oh yeah definitely need something better to handle arguments. I opened https://github.com/bnjbvr/cargo-machete/issues/12 back in the days, and having tried `gumdrop` since then, I quite like it.

**Comment by bnjbvr** [comment]
I'll take a stab at this, actually. Closing this one as dup of #12.
