### ISSUE TITLE
Fail if `Cargo.toml` annotations don't match what we expect

### ISSUE THREAD

**Issue by bnjbvr** [bnjbvr/cargo-machete#60]
It's easy to write `ignore = true` instead of `ignored = true` in the machete metadata section in a Cargo.toml file. Right now it'll fail the analysis of that specific package, but not overall; it might be better to make this a hard error instead, that fails the whole analysis (after displaying the analysis results for other crates).

**Comment by tottoto** [comment]
Can I take this issue?

**Comment by bnjbvr** [comment]
Sure, please go ahead and let me know if you need any help!

**Comment by tottoto** [comment]
Thanks! I will work on this.

**Comment by rolemadelen** [comment]
Hi @bnjbvr, is this issue still ongoing?

**Comment by bnjbvr** [comment]
hi @rolemadelen, thanks for the ping. Actually it's not anymore, because we consider the `ignored` vec as mandatory, *if* the `package.metadata.cargo-machete` annotation is present, so it will error with the following message if we use `ignore` instead of `ignored`:

```
error when handling ./integration-tests/ignored-dep/Cargo.toml: TOML parse error at line 14, column 1
   |
14 | [package.metadata.cargo-machete]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
missing field `ignored
```
