### ISSUE TITLE
Add a `check` command line param for CI

### ISSUE THREAD

**Issue by dessalines** [bnjbvr/cargo-machete#71]
This would be nice to have, then we could have it fail on our CI if someone added a dependency that is actually unused.

**Comment by bnjbvr** [comment]
Hi! `cargo machete` will return a status code if any unused dependencies have been found:

- 1 if there was at least one unused dependency
- 2 if there was an error during processing

Is this something you could use?

I think we could document this a bit better, and also just set up our github action so people can use this more easily.

**Comment by dessalines** [comment]
Ah okay, I didn't realize it returned proper status codes, that should work fine already then. Thanks!
