### ISSUE TITLE
xml-rs is always detected as unused

### ISSUE THREAD

**Issue by Eijebong** [bnjbvr/cargo-machete#8]
I guess cargo-machete doesn't understand the renaming happening here: https://github.com/netvl/xml-rs/blob/9c82a7664520e9c54996aefefed48014ca5cc4f6/Cargo.toml#L14

Repro:

```
cargo new --lib repro && cd repro
cargo add xml-rs
echo "pub use xml::*" > src/lib.rs
cargo machete
```

**Comment by bnjbvr** [comment]
Thanks for filing an issue! It's quite unclear how to detect this from `cargo-machete` itself, since we don't have access to renamings done by the crate which is getting published. Would be curious to know how frequently it's done in general in the Rust ecosystem.

**Comment by bnjbvr** [comment]
Note from lqd: consider using `cargo-metadata` for this, since it contains the public (effective) name for every dependency.
