### ISSUE TITLE
0.6.0 tagged but not released to crates.io

### ISSUE THREAD

**Issue by silwol** [bnjbvr/cargo-machete#90]
I saw that version 0.6.0 has been prepared in a commit, and there is a corresponding tag on the repository. In case this version is considered complete and final, could we please see a release on crates.io? The latest version I see there is 0.5.0.

**Comment by bnjbvr** [comment]
Doh! Thanks for letting me know, I forgot this crucial part of the release process 😅

**Comment by bnjbvr** [comment]
Should be done now!
