### ISSUE TITLE
False positives for multi-dep single `use` statements

### ISSUE THREAD

**Issue by Billy-Sheppard** [bnjbvr/cargo-machete#91]
Not sure if this is a known drawback of this crate, but my project has a rustfmt.toml that collapses all imports into one `use/pub use` `{}` block. This seems to cause all the crates to be returned as false positives.

```rust
pub use {async_trait, futures, reqwest};
```
```
cargo-machete found the following unused dependencies in /var/home/...
my_crate -- /var/home/ ... /Cargo.toml:
        async_trait
        futures
        reqwest
```

**Comment by bnjbvr** [comment]
Thanks for opening an issue; that looks like a real bug (in general, cargo-machete should give too many unused dependencies, not too few). Probably the regular expression would need to be tweaked, if you feel like investigating that using the [helper project](https://github.com/bnjbvr/cargo-machete/tree/main/regex-try), that could be fun and fixing that would be useful!
